### ISSUE TITLE
Dstike Watch v2 Support

### ISSUE THREAD

**Issue by ghost** [tomellericcardo/EVIL-ESP#3]
Hey. Sorry for opening another issue. I just got a dstike watch that runs deauther software from spacehuhn. Just wanted to know if you could update your project to support it. Maybe you could take a look at spacehuhn's project and modify it? That would be awesome if you can. Thanks.

**Comment by tomellericcardo** [comment]
Do you mean my project to support the hardware of the dstike watch or the software of the deauther by spacehuhn? Beacuse that is an Arduino project and this is a Micropython one... 
If you meant the hardware, I don't have one to make tests, but I think you just have to edit the configuration file. If not then let me know!
