### ISSUE TITLE
What is your password Wi-Fi

### ISSUE THREAD

**Issue by tomellericcardo** [tomellericcardo/EVIL-ESP#7]
What is your password Wi-Fi

_Originally posted by @iantot06 in https://github.com/tomellericcardo/EVIL-ESP/issues/1#issuecomment-827604333_

**Comment by tomellericcardo** [comment]
If you mean the password of the AP created when the device is on config mode, it's `ESPassword` as specified in the `data/config/config.json` file (you may want to change it by simply editing the file itself).

**Comment by JakeAndre** [comment]
Fresh setup, I can see a wi fi MicroPython-cf53a3  I type ESPassword to connect but it's wrong password ;( Am I missing something please ?
